Databases:
   VoxConverse: ../../SharedResources/AudioFiles/Project3/{uri}.wav

Protocols:
   VoxConverse:
      SpeakerDiarization:
          VoxConverseAudio:
           train:
              uri: ./Audio.development.lst
              annotation: ./Audio.development.rttm
              annotated: ./Audio.development.uem
           development:
              uri: ./Audio.development.lst
              annotation: ./Audio.development.rttm
              annotated: ./Audio.development.uem
           test:
              uri: ./Audio.development.lst
              annotation: ./Audio.development.rttm
              annotated: ./Audio.development.uem
